### ISSUE TITLE
Getting current mq on page load not working

### ISSUE THREAD

**Issue by chadwatson** [40Digits/jquery-mq-sync#6]
Trying to check the current media query when the page loads, but can't get it to work. I did some debugging in mqSync.js...

```
init: function (options) {
	// Initialize the media query
	this.currentMediaQuery = this.fetchMediaQuery();
	$('body').data('media-query', this.currentMediaQuery);
	console.log($('body').data()); //<----
	// On window resize, set media query var
	$(window).resize(this.onResize);
}
```
I get the following in the console:

```
Object {mediaQuery: "Times"}
```

Times??

**Comment by ckhicks** [comment]
I've noticed a need to trigger the resize event upon first load in the 
past. Though, in this case, it may be that your font-family isn't being 
set by CSS at all, since you're seeing Times New Roman as the current 
attribute.

**Comment by chadwatson** [comment]
I just realized that I was using an old version of the script. Forgot the things were changed to use `head` instead of `html`. Thanks for the response, CK!
